import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { ClerkProvider } from "@clerk/nextjs";
import Navbar from "@/components/common/navbar";
import AppSidebar from "@/components/common/app-sidebar";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ClerkProvider afterSignOutUrl="/">
            {/* <SidebarProvider> */}
                <html lang="en">
                    <body className={`${geistSans.variable} ${geistMono.variable} antialiased w-screen h-screen`}>
                        <header>
                            <Navbar />
                        </header>
                        <main className="w-full h-[calc(100%-60px)]">
                            <Toaster />
                            {children}
                        </main>
                    </body>
                </html>
            {/* </SidebarProvider> */}
        </ClerkProvider >
    );
}
